### ISSUE TITLE
Where to find swagger.json file

### ISSUE THREAD

**Issue by yadavan88** [swagger-akka-http/swagger-akka-http#10]
I am trying to use swagger for 2 purposes :

1. For API Documentation and reference
2. To provide a set of API's which can be used by other applications

Using swagger-akk-http, I am able to generate the documentation and view in the Swagger-UI. But for my 2nd requirement, I need to transform the swagger.json file. I need multiple types of filter for the api's. For doing that, I was trying to find out the location of the swagger json file, but I am not able to find it. Is it not generated and saved in the workspace ? Or is it read every time using reflection on annotations ?

**Comment by pjfanning** [comment]
The swagger.json file is generated every time it is requested.
This code is in the SwaggerHttpService class (look for swagger.json).
If you want manipulate the generated JSON, you could subclass this class and override toJsonString(s: Swagger).

**Comment by yadavan88** [comment]
Okay, Thank you very much. I shall try that.
