### ISSUE TITLE
What configure PropertyNamingStrategy.SNAKE_CASE with Jackson?

### ISSUE THREAD

**Issue by tardelli013** [swagger-akka-http/swagger-akka-http#119]

**Comment by pjfanning** [comment]
swagger-akka-http supports generating swagger schemas based on your akka-http code - you can control names by using snake-case in your function names (the norm in scala and java). You can use swagger annotations to override certain values.

**Comment by tardelli013** [comment]
> swagger-akka-http supports generating swagger schemas based on your akka-http code - you can control names by using snake-case in your function names (the norm in scala and java). You can use swagger annotations to override certain values.

Thanks, resolved with annotation model.
```java
@JsonNaming(classOf[SnakeCaseStrategy])
