### ISSUE TITLE
Problems with new scala model converter.

### ISSUE THREAD

**Issue by xaoc3dgraph** [swagger-akka-http/swagger-akka-http#15]
Hi devs!
After migration from spray to akka-http we have lot of problems with swagger - our docs not usable anymore, because scala model converter is so "hungry", it converts all implicits and convert them to body parameters, do not understand Enumerations. 
I've tried add classes to ignore, but no luck. Model converter skip this configuration...

So my question is - how to downgrade to model converter used in swagger-spray?
Can you help me?

**Comment by pjfanning** [comment]
Swagger-akka-http is just a thin wrapper for the swagger api tools. I suggest you log a stackoverflow question or request enhancements in swagger-scala-module.

**Comment by xaoc3dgraph** [comment]
Ok, thanks.

**Comment by NeQuissimus** [comment]
@xdev-developer Did you ever find a solution to this?

**Comment by xdev-developer** [comment]
@NeQuissimus nope 
I use custom implementation - last "swagger-spray version" modified to akka-http support.
