### ISSUE TITLE
Is there a way to put boolean query params as an optional parameters. Currently it seems I can just have boolean to be selected as either true or false from Swagger-UI

### ISSUE THREAD

**Issue by mikip91** [swagger-akka-http/swagger-akka-http#155]
I have a business requirement where for a boolean value i can either pass true or false or not selected(Null) as query params. If the value selected is Null then query params should not be used when generating a url for the request and should be completely optional. Please tell me a way do achieve this

**Comment by pjfanning** [comment]
duplicates https://github.com/pjfanning/swagger-akka-http-sample/issues/11
