### ISSUE TITLE
Generating json throws com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Direct self-reference leading to cycle

### ISSUE THREAD

**Issue by alexmnyc** [swagger-akka-http/swagger-akka-http#162]
Generating json throws com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Direct self-reference leading to cycle

**Comment by pjfanning** [comment]
Unless you can provide a test case, there is not much I can do. swagger-akka-http is unit tested and works in the samples like the one listed on https://github.com/swagger-akka-http/swagger-akka-http#examples

**Comment by pjfanning** [comment]
I've seen this issue with swagger-akka-http 1.1.1 and jackson 2.10.3/2.10.4
