### ISSUE TITLE
Support Akka HTTP 10.0.0 final

### ISSUE THREAD

**Issue by hseeberger** [swagger-akka-http/swagger-akka-http#17]

**Comment by pjfanning** [comment]
Hi Heiko. I have changed the akka-http version in build.sbt. I'll publish a new jar when I return from vacation. My signing key is on my work laptop.

**Comment by hseeberger** [comment]
Enjoy your vacation ;-)

**Comment by pjfanning** [comment]
0.8.0 is now released
