### ISSUE TITLE
Problem finding SwaggerScalaModelConverter

### ISSUE THREAD

**Issue by tompro** [swagger-akka-http/swagger-akka-http#19]
When upgrading to akka-http 10 and using swagger-akka-http (version 0.7.1 and 0.8.1) I am getting a runtime error when calling the swagger.json route with:
`Exception thrown io.swagger.converter.ModelConverter: Provider io.swagger.scala.converter.SwaggerScalaModelConverter could not be instantiated`

**Comment by tompro** [comment]
Found others having that same issue:
http://stackoverflow.com/questions/41102982/swagger-akka-http-not-working-after-upgrading-akka-2-4-14

**Comment by pjfanning** [comment]
https://github.com/pjfanning/swagger-akka-http-sample has a simple example that uses Akka-Http 10.0.0 and that works.
The core swagger.io code is tied to Jackson 2.4.x. Could you check your application to see if it is using a newer version of Jackson?
https://github.com/pjfanning/swagger-akka-http-sample has a scala 2.12 branch where I do get the sample to work with a newer Jackson jar (this branch also works in scala 2.11). To get it to work though, I had to patch the core swagger code.

**Comment by tompro** [comment]
You are right the project depends on Jackson 2.7.x. I have tried to build the 2.12 (0.8.2-SNAPSHOT) but your patches to swagger core seem to be published local (obviously ;) ). Thanks for the quick response. I'll have to wait for a working version before I can further migrate the project then.

**Comment by pjfanning** [comment]
The patched swagger core jars are hosted at jipack.
In sbt, use:
resolvers += "jitpack" at "https://jitpack.io"
resolvers += Resolver.sonatypeRepo("snapshots")

**Comment by tompro** [comment]
Wow that's cool jitpack ! I didn't know that exists. I'll give it a try. Thanks a lot!

**Comment by tompro** [comment]
And yes this already works like a charm!
