### ISSUE TITLE
generate swagger docs from yaml file

### ISSUE THREAD

**Issue by mazorigal** [swagger-akka-http/swagger-akka-http#20]
Hi,

is it possible to create the swagger docs from a provided swagger yaml file instead of using annotations in the code it self and let swagger-akka-http to generate all automatically ?

Thanks,

**Comment by pjfanning** [comment]
swagger-akka-http only works with swagger annotations

**Comment by mazorigal** [comment]
Would it be posdible to add support for yaml files?

**Comment by pjfanning** [comment]
It's not something that was on my radar. Would you be able to try building yourself?

**Comment by mazorigal** [comment]
sorry, dont think that I would have time for that in the near future.
But just to understand where changes would need to be made.
is only what needed is to change the behaviour of generateSwaggerDocs function ?
so generateSwaggerDocs should simply read the yaml file and convert it to a json file ?

**Comment by pjfanning** [comment]
Maybe the approach you can use is to add a route to your akka-http routes like swagger-akka-http does and that uses something like https://github.com/FasterXML/jackson-dataformat-yaml/ to read your yaml and then reserialise it as json.

**Comment by pjfanning** [comment]
Swagger UI can load yaml files (https://github.com/swagger-api/swagger-ui/issues/1047). So why do you need to translate to JSON?
I quickly tried out taking the existing swagger-akka-http support to also allow yaml output but the http://petstore.swagger.io/ wouldn't load the yaml I generated. The format looked similar to samples like https://gist.github.com/earth2marsh/264123aefc2e29551d9d but some of the values in my yaml were quoted. I might still add this as an experimental feature.

**Comment by mazorigal** [comment]
If not yaml to json needed, then even better.
Would be great if you can add it as experimental feature.

Am 15.12.2016 4:59 nachm. schrieb "PJ Fanning" <notifications@github.com>:

**Comment by pjfanning** [comment]
The idea of swagger-akka-http is to generate swagger models based on case class definitions. If you already have the swagger yaml then you can just use built-in directives to publish the static yaml - http://doc.akka.io/docs/akka-http/current/scala/http/routing-dsl/directives/file-and-resource-directives/index.html#fileandresourcedirectives

**Comment by mazorigal** [comment]
Thanks, sound good.
Regarding case classes, is swagger-akka-http can work as well with inherence ?
I have the following:
```
trait Dim

  case class Color(name: String, html: String) extends Dim
  case class Price(mean: Double, min: Double, max: Double) extends Dim
  case class Foo(x: Dim)
```

but in swagger I get:
Model:
```
Foo {
x (Dim, optional)
}
Dim {}
```

and for Example:
```
{
  "x": {}
}
```

Is there any way to specify all the possible responses schemas  ?

**Comment by pjfanning** [comment]
swagger doesn't support anything like the xml schema choice - apparently, will be in the next swagger spec (3.0, I'm guessing) - https://groups.google.com/forum/#!topic/swagger-swaggersocket/LXnWjhxfl74
