### ISSUE TITLE
Disable swagger api and document generation.

### ISSUE THREAD

**Issue by githubmo** [swagger-akka-http/swagger-akka-http#209]
Due to the fact that generated Open API javascript produces critical errors from our SAST (Gitlab Gemnasium), is there a way for us to disable swagger document generation. This would be useful for us to stop it being generated and packaged in our jars for our production environments.

**Comment by pjfanning** [comment]
Can't you just remove this dependency from your application?

**Comment by pjfanning** [comment]
Closing due to lack of details.
