### ISSUE TITLE
response model Map

### ISSUE THREAD

**Issue by mazorigal** [swagger-akka-http/swagger-akka-http#22]
Hi,

I have a response which looks like that:
```case class Foo(x: String, y: Int)```

response -> ```Map[String, Foo]```
example: ```Map("key1" -> Foo("v1", 1), "key2" -> Foo("v2", 2))```

I am using circe, so eventually the JSON response looks like:
```{"key1": {"x": "v1", "y": 1}, "key2": {"x": "v2", "y": 2})```

how can I define the schema of the response with swagger ?
If I use responseContainer="Map" I get in swagger
exmple: ```{}```
model: ```inline_model {}```

Thanks,

**Comment by pjfanning** [comment]
@mazorigal I'd prefer if you put swagger usage queries on stackoverflow. This open source project is just a thin wrapper to allow people to use the core swagger annotations in akka-http.
The main use case for me is supporting case classes. With Map[String, Foo], the keyName(s) is unknown so the model is abstract.

**Comment by pjfanning** [comment]
http://stackoverflow.com/questions/36136885/swagger-map-of-string-object
