### ISSUE TITLE
How change swagger doc to Swagger 2.0.x specification instead of OpenApi 3 ?

### ISSUE THREAD

**Issue by FeRulo** [swagger-akka-http/swagger-akka-http#229]
according to readme file: 2.4.0	stable	master	Supports Swagger 2.0.X and OpenAPI 3.0 Specification.

**Comment by pjfanning** [comment]
updated README to hightlight that the first bit is abouy swagger libraries and the 2nd bit is about the spec - I'm afraid it's not my fault that swagger libs and the specs follow different version naming
