### ISSUE TITLE
How can I generate the complete API path when my routing are split into multiple classes?

### ISSUE THREAD

**Issue by HoaiDang-work** [swagger-akka-http/swagger-akka-http#233]
My API routing is organized as below. The example getUser method is generated in swagger as /users/{userId}. Is there a way to generate the full path from the root route, /v1/user_management/users/{userId}?

@Path("/v1")
public class Routes extends AllDirectives {
  
  private Route createSubRoutes() {
     userManagementRouter.createRoute(),
     deviceManagementRouter.createRoute()
  }
}

@Path("/user_management")
public class UserManagementRouter extends BaseRouter {
  public Route createRoute() {
      return pathPrefix("user_management", () ->
          route(
              userRouter.createRoute(),
              companyRouter.createRoute()
          )
      );
    }
}

@Path("/users")
@Tag(name = "users")
public class UserRouter extends CipherRouter {
  public Route createRoute() {
      return pathPrefix("users", () ->
          route(
              getUser(),
              saveUser()
          )
      );
    }

  @Path("/{userId}")
    @GET
    @Operation(
        description = "Endpoint to get user by ID",
        method = "GET",
        parameters = {
            @Parameter(name = "userId", in = ParameterIn.PATH, description = "User ID")
        },
        responses = {
            @ApiResponse(responseCode = "200", description = "Succeeded", content = @Content(schema = @Schema(implementation = Response.class), mediaType = MediaType.APPLICATION_JSON)),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = @Content(schema = @Schema(implementation = Response.class), mediaType = MediaType.APPLICATION_JSON)),
            @ApiResponse(responseCode = "403", description = "Forbidden", content = @Content(schema = @Schema(implementation = Response.class), mediaType = MediaType.APPLICATION_JSON)),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = @Content(schema = @Schema(implementation = Response.class), mediaType = MediaType.APPLICATION_JSON))
        }
    )
    public Route getUser() {
      return get(() ->
        //do something here
      );
    }
}

**Comment by pjfanning** [comment]
swagger-akka-http is for scala projects only -- we don't support java

**Comment by pjfanning** [comment]
Closing old issue - please reopen if you extra detail to provide.
