### ISSUE TITLE
add back ability to set schemes in Java API

### ISSUE THREAD

**Issue by HoaiDang-work** [swagger-akka-http/swagger-akka-http#234]
I'm unable to use the like of val schemes = List(Scheme.HTTPS) to select the schemes I would like to use anymore. What is the recommended way to set it with the newer version? It always default to server = "http://" now. swagger-akka-http is correctly figuring out the scheme:host/basePath to use, can we default the "Server" to that?

**Comment by pjfanning** [comment]
schemes is List[String] -- what type is Scheme.HTTPS

**Comment by pjfanning** [comment]
You didn't answer my question - what type is Scheme.HTTPS?

**Comment by HoaiDang-work** [comment]
There is used to be an enum in swagger-models jar

public enum Scheme {
    HTTP("http"),
    HTTPS("https"),
    WS("ws"),
    WSS("wss");
}

**Comment by pjfanning** [comment]
So I checked the code and the scheme support has been removed. I can add it back in the next version. I can't find Scheme in the latest swagger-models jar and the latest swagger-akka-http code treats scheme as a String (scala API still supports scheme, just Java API has lost this).

This should work when new version is released.
```
public List schemes() {
return List.of("http", "https");
}
```

**Comment by pjfanning** [comment]
https://github.com/swagger-akka-http/swagger-akka-http/commit/e1b508804d08040edec0a459e3990167edf33c04 is the fix

**Comment by HoaiDang-work** [comment]
When will the new version be the next release?

**Comment by HoaiDang-work** [comment]
May I ask when the next release is planned?

**Comment by pjfanning** [comment]
2.4.1-SNAPSHOT is published - I might release 2.4.1 at weekend

**Comment by pjfanning** [comment]
v2.4.1 is released

**Comment by HoaiDang-work** [comment]
Can you also add the ability to set host and securityRequirement to Java API? Selecting only scheme did not work for me, for example, https://petstore.swagger.io/ resolves host incorrectly, while SwaggerHub disables "Try it out" because there are no servers specified. I think I need to explicitly config the host to use but currently, I see no other way other than adding @Server to every resources classes. Reading Scalar SwaggerGenerator, it looks like scala API can config a global default host (I'm not familiar with Scala to be sure).

The same for securityRequirement, I can config the global security schemes to use but to apply them to the operations, I need to use explicit @SecurityRequirement, I don't see a way to make it a global config.

**Comment by pjfanning** [comment]
have you tried overriding host method as per https://github.com/swagger-akka-http/swagger-akka-http#java-dsl-swaggergenerator ?

For security reqs, have you tried overriding this?

```
@Override
public Map<String, SecurityScheme> securitySchemes {
  //populate map here
  return map;
}
```

swagger-akka-http does not support setting List<SecurityRequirement> and probably should.

**Comment by HoaiDang-work** [comment]
I don't have the option to override host method anymore in 2.4.1. I used to have it in 0.14.0 (your sample project).

Regarding security reqs, I overrode securitySchemes:
   ```
 @Override
    public Map<String, SecurityScheme> securitySchemes() {
      var securityScheme = new SecurityScheme();
      securityScheme.setType(Type.HTTP);
      securityScheme.setScheme("bearer");
      securityScheme.setBearerFormat("JWT");
      securityScheme.setIn(In.HEADER);
      securityScheme.setName("Authorization");
      return Map.of("bearer-jwt", securityScheme);
    }
```
But I still need to add @SecurityRequirement with the security scheme's name bearer-jwt to the class or method for the security scheme to be applied to that class or method. Any steps missed?

**Comment by pjfanning** [comment]
@HoaiDang-work v2.4.2 is released

**Comment by pjfanning** [comment]
@HoaiDang-work would you be interested in creating a small sample java project for the latest swagger-akka-http? - I can link to it on the README of this project

**Comment by HoaiDang-work** [comment]
Sure, i will clean up the sample project and send you the link.
