### ISSUE TITLE
Support Swagger 1.5.11 so "format" can be set for ApiImplicitParams

### ISSUE THREAD

**Issue by amupoti** [swagger-akka-http/swagger-akka-http#28]
It would be great to support Swagger 1.5.11 so "format" can be set for ApiImplicitParams. 
This would allow automatic tools like https://bitbucket.org/atlassian/swagger-request-validator to check the format of the type (int32/int64 for int types), as it is defined in the standard

**Comment by pjfanning** [comment]
This will be supported in swagger-akka-http 0.9.0 which I will release as soon as swagger-scala-module 1.0.3 is published. swagger-akka-http 0.9.0-SNAPSHOT is available in OSS sonatype snapshots repo.

**Comment by amupoti** [comment]
Thanks! I am now using 1.5.12 and I am able to pass the format to the ApiImplicitParam.

```scala
  @ApiImplicitParams(Array(
    new ApiImplicitParam(name = "newsstand_id", value = "id of the newsstand", 
    dataType = "integer", paramType = "path", format = "int32")
  ))
```

However, the swagger generated is as follows (no format field is created):

```json
"parameters": [
{
"name": "newsstand_id",
"in": "path",
"description": "id of the newsstand",
"type": "integer",
"required": true
}
],
```

I think I'll wait for release 0.9. Thanks again!

**Comment by pjfanning** [comment]
0.9.0 released https://github.com/swagger-akka-http/swagger-akka-http/pull/30

**Comment by marrufatzinio** [comment]
Thanks for all the pointers so far. The new release fixed the problems.

**Comment by amupoti** [comment]
Thanks for all the pointers so far. The new release fixed the problems.
