### ISSUE TITLE
Swagger-akka-http with UI built using webjar

### ISSUE THREAD

**Issue by gerbrand** [swagger-akka-http/swagger-akka-http#282]
In the example-application, [my pr](https://github.com/pjfanning/swagger-akka-http-sample/pull/16) is just merged so the example now contains a swagger ui out-of-the-box. Could we add this functionality as default functionality too to this module?

To avoid breaking existing installations (that presumably already have the UI) I thought of two options I thought to create a new module then extends/reuses the currrent swagger-akka-http module with a built-in ui using webjar. So people that want to use swagger with akka, and want a UI could use the that new module, for people using the existing module nothing will change.

I'll create a new repository, but if you want you can add the repository under the github organization. Alternatively, swagger-akka-http could also be turned into a multi-module project, so the swagger-akka-http-with-ui module stays in the same repository.

**Comment by pjfanning** [comment]
> Thanks for updating the readme. I don't want to update the original swaggerUI, but I have created module that extends the existing one, similar to the sample: https://github.com/gerbrand/swagger-akka-http-with-ui Do you think that repo is useful to add to the organization account?

Possibly. I'll look at it in coming days.

**Comment by pjfanning** [comment]
https://github.com/swagger-akka-http/swagger-akka-http-with-ui/runs/3847916082?check_suite_focus=true -- publishes https://github.com/swagger-akka-http/swagger-akka-http-with-ui 2.6.0 to maven-central

I'd prefer not to use swagger-akka-http-with-ui in the existing sample but if you want to clone that and use swagger-akka-http-with-ui, feel free to do so
