### ISSUE TITLE
Swagger generates empty schemas

### ISSUE THREAD

**Issue by andreiherdes** [swagger-akka-http/swagger-akka-http#289]
Hello!
I'm trying to expose Swagger for my API, but found out that schemas are empty when deploying the service in a docker container, as you can see below:

![image](https://user-images.githubusercontent.com/26523319/139684765-512145e3-177f-479e-83d8-bc9df3f80ada.png)

I was expecting to have the schemas filled in with the proper case class attributes:

![image](https://user-images.githubusercontent.com/26523319/139684834-89d88870-e203-40c8-b5bb-1bd4cbac6293.png)

Used the configuration provided in [swagger-akka-http-sample](https://github.com/pjfanning/swagger-akka-http-sample):

```
lazy val swaggerVersion = "2.1.11"

val swaggerDependencies = Seq(
  "jakarta.ws.rs" % "jakarta.ws.rs-api" % "3.0.0",
  "com.github.swagger-akka-http" %% "swagger-akka-http" % "2.6.0",
  "com.github.swagger-akka-http" %% "swagger-scala-module" % "2.5.2",
  "com.github.swagger-akka-http" %% "swagger-enumeratum-module" % "2.3.0",
  "io.swagger.core.v3" % "swagger-jaxrs2-jakarta" % swaggerVersion
)

val swaggerUIDependencies = Seq(
  "org.webjars" % "webjars-locator" % "0.42",
  "org.webjars" % "swagger-ui" % "3.52.5",
)
```

Am I missing something or is this a bug? Found a similar issue [here](https://github.com/nestjs/swagger/issues/459)
Thanks!

**Comment by pjfanning** [comment]
Could you attach the actual swagger.json? I might be able to debug that.

**Comment by andreiherdes** [comment]
Hey! Sure. Attaching the following:

- swagger-local.json generated when starting Main on my local machine
- swagger-docker.json generated when starting the app in a Docker container

[swagger.zip](https://github.com/swagger-akka-http/swagger-akka-http/files/7458795/swagger.zip)
 
The schema properties are missing in the second scenario.

**Comment by pjfanning** [comment]
I'm afraid if this is just happening in your docker setup, I'm going to have to leave it to you to debug.

**Comment by andreiherdes** [comment]
I'm building my docker image using sbt assembly. I assume that the issue lies within the merge strategy, as at first the swagger-ui html data was discarded, and fixed it by adding this:

```
assembly / assemblyMergeStrategy := {
  case PathList("META-INF", "resources", "webjars", "swagger-ui", _ @ _*) => MergeStrategy.first
  case PathList("META-INF", _ @ _*) => MergeStrategy.discard
  case PathList("reference.conf") => MergeStrategy.concat
  case _ => MergeStrategy.first
}
```

Not sure what else I'm missing in order to have the schemas properly populated. Any chance you have used this setup in the past? :smile:

**Comment by pjfanning** [comment]
If you want swagger UI to be embedded in your app, could you look at https://github.com/swagger-akka-http/swagger-akka-http-with-ui ?

**Comment by andreiherdes** [comment]
Thanks, already had a look

**Comment by andreiherdes** [comment]
After debugging and testing I realized that my custom assembly configuration was discarding swagger data. Updated the configuration to the [default one](https://github.com/sbt/sbt-assembly) and now it works :+1:
Thanks!
