### ISSUE TITLE
Any plans to release stable version 0.9.0 to support Scala 2.12 ?

### ISSUE THREAD

**Issue by sheinbergon** [swagger-akka-http/swagger-akka-http#29]
10x

**Comment by pjfanning** [comment]
This will be released as soon as swagger-scala-module 1.0.3 is published. swagger-akka-http 0.9.0-SNAPSHOT is available in OSS sonatype snapshots repo.

**Comment by pjfanning** [comment]
0.9.0 released https://github.com/swagger-akka-http/swagger-akka-http/pull/30
