### ISSUE TITLE
Some endpoints don't get generated, but with no error??

### ISSUE THREAD

**Issue by mebigfatguy** [swagger-akka-http/swagger-akka-http#293]
I am using swagger-akka-http 2.6.0 on a akka_2.13 java codebase.

I have various endpoints annotated with swagger annotations in a class. The class generates correct swagger documentation, except one of the endpoints is not produced. it is completely missing. I see no hidden properties used in the swagger annotations. The annotations used in this endpoint, are no different (so far as i can tell) to the ones used in endpoints that work fine.

Is there a way to debug why this endpoint is skipped over?

The endpoint that is lost is

    @POST
    @Path("/" + RouteDirectory.GETLINKEDGROUPBULKDATA)
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces(MediaType.APPLICATION_JSON)
    @Operation(summary = "View data for all linked groups",
            description = "Send a request to this end point to view all linked group data in a stripe for specified ids")
    @Parameter(name = LinkedGroupRequest.QP_HIER_STATUS, in = ParameterIn.QUERY)
    @ApiResponse(responseCode = "200", description = SwaggerAPIMessages.RES_VIEW_200,
            content = @Content(schema = @Schema(implementation = LinkedGroupBulkDataResult.class)))
    @ApiResponse(responseCode = "500", description = "An unexpected error occurred while fetching bulk linked group information.")
    @ApiResponse(responseCode = "400", description = SwaggerAPIMessages.RES_400)
    /* ignored parameter is only for Swagger and unused */
    private Route getLinkedGroupBulkData(@Context FileSharedServiceRequestContext context, @RequestBody(required = true) LinkedGroupBulkDataRequest ignored) {

**Comment by pjfanning** [comment]
There is nothing obvious in the code snippet. The code that builds the swagger json/yaml is in SwaggerGenerator trait.

```
val swagger: OpenAPI = reader.read(apiClasses.asJava)
```

So you need to override the apiClasses value to ensure that classes are analysed. Try using your using your IDE to step through the code around this point. Maybe you could compare what you've coded with the https://github.com/pjfanning/swagger-akka-http-sample

**Comment by mebigfatguy** [comment]
The odd thing is other methods in that same class generate fine. just that one.

ok, i'll have to figure out how to get akka usable in eclipse.

**Comment by pjfanning** [comment]
Closing old issue - please reopen if you extra detail to provide.
