### ISSUE TITLE
Question : How can I specify one or more base URLs for the API using an array of servers?

### ISSUE THREAD

**Issue by JiYoung-Kwon** [swagger-akka-http/swagger-akka-http#321]
OpenAPI 2.0 (Swagger 2.0) only supports a single host with multiple schemes (HTTP/HTTPS/etc.)

Currently, OpenAPI 3.0 supports multiple hosts with different schemes and base paths.
https://swagger.io/docs/specification/api-host-and-base-path/

Is there a way to specify multiple hosts?

**Comment by pjfanning** [comment]
Currently, we only seem to support 1 host/port - see https://github.com/pjfanning/swagger-akka-http-sample/blob/main/src/main/scala/com/example/akka/swagger/SwaggerDocService.scala#L20

If you would like to submit a PR, I will look at it. I'm currently on vacation so it might take me a while to respond.

**Comment by pjfanning** [comment]
#327 is merged
