### ISSUE TITLE
Gitter room or similar place to ask simple questions

### ISSUE THREAD

**Issue by stewSquared** [swagger-akka-http/swagger-akka-http#33]
Hi! I'd like a place to ask simple questions like, say, where is the sequence of modelTypes mentioned in the README defined?

Might you be willing to take 5 minutes and add a gitter channel for swagger-akka-http?

**Comment by pjfanning** [comment]
gitter badge added

**Comment by stewSquared** [comment]
Great! Thank you. The channel seems to be private though; could you open it up publicly?

**Comment by pjfanning** [comment]
Does https://gitter.im/swagger-akka-http/Lobby work? I've never used gitter but the app claims anyone can join the room.

**Comment by stewSquared** [comment]
Yes, that one works for me, but you might want to fix the project gitter badge if that's the one you want to use publicly.
