### ISSUE TITLE
Post always returning a 200

### ISSUE THREAD

**Issue by kevinpauli** [swagger-akka-http/swagger-akka-http#37]
I have a resource where a POST should return a 202 Accepted, since it is a long-running operation.  So I have

```
@ApiOperation(value = "Create scenario", httpMethod = "POST")
  @ApiResponses(Array(
    new ApiResponse(code = 202, message = "Scenario creation in progress"),
    new ApiResponse(code = 500, message = "Internal server error")
  ))
```

However responses generated includes a 200, which I do not want:

```
"responses" : {
          "200" : {
            "description" : "successful operation",
            "schema" : {
              "$ref" : "#/definitions/Function1RequestContextFutureRouteResult"
            }
          },
          "202" : {
            "description" : "Scenario creation in progress"
          },
          "500" : {
            "description" : "Internal server error"
          }
```

**Comment by pjfanning** [comment]
Move the default response code to the `@ApiOperation`

`
@ApiOperation(code = 202, value = "Create scenario", httpMethod = "POST")
  @ApiResponses(Array(
    new ApiResponse(code = 500, message = "Internal server error")
  ))
`

**Comment by kevinpauli** [comment]
That was it!  Thanks, and sorry if that is in the docs somewhere...
