### ISSUE TITLE
Cannot find reference model when `paramType` is `header`

### ISSUE THREAD

**Issue by zailushangde** [swagger-akka-http/swagger-akka-http#38]
Hi! Like the title said: `Authorization` is going to be treated as `header`, but the generated swagger code cannot find the reference model as below
```
- name: "authorization"
        in: "header"
        description: "Bearer authorization token"
        required: true
        type: "models.Authorization"  // <-----
```
However, when changing `paramType` to `body`, it can find the model Authorization:
```
- in: "body"
        name: "authorization"
        description: "Bearer authorization token"
        required: true
        schema:
          $ref: "#/definitions/Authorization"
```
Unfortunatly this doesn't meet the requirement to make Authorization as `header`.

Env:
Scala - 2.12.2 
swagger-akka-http - 0.9.1
akka-http - 10.0.5

Besides, the following is the way to apply parameter information:
```
  @ApiOperation(value = "Get brand family", httpMethod = "GET", response = classOf[BrandFamily])
  @ApiImplicitParams(Array(new ApiImplicitParam(name = "Authorization", value = "Bearer authorization token", dataType = "models.Authorization", paramType = "header", required = true)))
  @ApiResponses(Array(
    new ApiResponse(code = 400, message = "Bad Request"),
    new ApiResponse(code = 401, message = "Unauthorized"),
    new ApiResponse(code = 403, message = "Forbidden")
  ))
```

**Comment by pjfanning** [comment]
In Swagger, authorization headers are specified using Security Definitions.
https://stackoverflow.com/questions/32910065/how-can-i-represent-authorization-bearer-token-in-a-swagger-spec-swagger-j
http://swagger.io/docs/specification/authentication/
https://github.com/pjfanning/swagger-akka-http-sample has some code to enable basic auth.

**Comment by zailushangde** [comment]
oh, it is great. Thanks a lot.

After defining `securitySchemeDefinitions` as `OAuth2Definition`, It seems the library doesn't support adding the `security` section on the root level or operation level, right?
What I expected is:
```
paths:
  /brands
    get:
      ...
      security:  // <-----
        - oauth2
          - brands.read
```

**Comment by zailushangde** [comment]
Got it from https://stackoverflow.com/questions/38267272/how-to-use-swagger-with-akka-http-basic-auth
