### ISSUE TITLE
Java Usage

### ISSUE THREAD

**Issue by synox** [swagger-akka-http/swagger-akka-http#39]
I don't know how to use the Scala API in Java. Could you please provide a java example?

**Comment by pjfanning** [comment]
This is the first time I've come across anyone using akka or akka-http using the Java API/DSL. One option would be to use the Scala sample (https://github.com/pjfanning/swagger-akka-http-sample) and to use this to wire together the HTTP server and the routing DSL but in the `complete` calls in the Service classes, you could replace that with Java code.
Scala code can easily use Java classes. For Java code to use Scala classes, this usually requires that the Scala code has a Java friendly API.

**Comment by pjfanning** [comment]
With the Java sample code in http://doc.akka.io/docs/akka-http/10.0.7/java/http/routing-dsl/index.html, it should be possible to add Swagger annotations. The MinimalHttpApp routes method would need to concat an instance of swagger-akka-http SwaggerDocService routes.
https://github.com/lomigmegard/akka-http-cors now has Java support.

**Comment by pjfanning** [comment]
I added a very simplistic Java demo - https://github.com/pjfanning/swagger-akka-http-java
That demo does not use swagger-akka-http jar but uses swagger.io jars directly.

**Comment by pjfanning** [comment]
Provided a basic sample
