### ISSUE TITLE
How to provide example input for body parameter for HTTP POST

### ISSUE THREAD

**Issue by eswenson1** [swagger-akka-http/swagger-akka-http#40]
I want to provide example JSON for the body of an HTTP POST request.  If I provide a 

new ApiImplicitParam(
        name = "body",
        required = false,
        dataType = "string",
        paramType = "body"
        example = "{foo: bar}"
      )
I end up with two "body" parameters in the swagger.json and in the rendered UI.  How do I REPLACE the default "body" parameter so that I can provide an example?

**Comment by pjfanning** [comment]
If you are binding the JSON text to an object instance, I would recommend using dataTypeClass=classOf[MyClass].
This will lead to a swagger model being added to your swagger doc.
The swagger UI can then generate a sample request based on the swagger model.

**Comment by eswenson1** [comment]
The body is an arbitrary JSON object (with no-schema-defined name/value pairs). So I can't define a type (other than Map[String,String]) for it.  I tried Map[String,String] but that didn't work. In any case, my problem is that I end up with two "body" parameters in my generated swagger.json (and in the web page that results). I only want a single "body" parameter.

**Comment by pjfanning** [comment]
The swagger doc generation is done using io.swagger:swagger-jaxrs. It would probably be better to raise an issue there and provide sample code.

**Comment by eswenson1** [comment]
Yes, I realized that after creating the ticket.

**Comment by pjfanning** [comment]
Closing, as no work is needed in swagger-akka-http.
