### ISSUE TITLE
HasActorSystem trait should have not ActorMaterializer but just Materializer as member

### ISSUE THREAD

**Issue by manonthegithub** [swagger-akka-http/swagger-akka-http#43]
I see current implementation:
```scala
trait HasActorSystem {
  implicit val actorSystem: ActorSystem
  implicit val materializer: ActorMaterializer
}
```
But ActorMaterializer is implementation of Materializer and akka-http actually needs just Materializer

**Comment by pjfanning** [comment]
I'd be reluctant to make a change that might break compatibility for existing users

**Comment by pjfanning** [comment]
Can we keep this to one issue? https://github.com/swagger-akka-http/swagger-akka-http/issues/44
