### ISSUE TITLE
Does SwaggerHttpService really need to be HasActorSystem?

### ISSUE THREAD

**Issue by manonthegithub** [swagger-akka-http/swagger-akka-http#44]
Does SwaggerHttpService really use any of the members of HasActorSystem? At first glance I don't see any so why HasActorSystem must be self type of it? I my case it is redundant because I already have trait like HasActorSystem and I want to extend my trait, so reimplementing its fields is redundant for me.

**Comment by pjfanning** [comment]
It may be possible to get rid of it but as with https://github.com/swagger-akka-http/swagger-akka-http/issues/43 I'd be reluctant to make changes that affect compatibility. Maybe, I'll refactor when there is a major release. I expect to release a new version after swagger 3.0 tooling is released.

**Comment by pjfanning** [comment]
https://github.com/pjfanning/swagger-akka-http-sample/blob/master/src/main/scala/com/example/akka/swagger/SwaggerDocService.scala has a sample of the current code is used

**Comment by manonthegithub** [comment]
Yeah, I've seen examples, but it is not convenient to specify materializer and system which are not really needed). I'll look forward for the new version)

**Comment by pjfanning** [comment]
HasActorSystem trait removed in 0.10.0-SNAPSHOT

**Comment by manonthegithub** [comment]
great! thanks!
