### ISSUE TITLE
Not setting a 'response' on a ApiOperation leads "Funtion1" identified as a definition 

### ISSUE THREAD

**Issue by CristianPupazan** [swagger-akka-http/swagger-akka-http#45]
I got an OPTIONS method that does not return a body. If I don't set the response and leave it to default to `response = classOf[Void]` a new object definition appears in the swagger json:
`"definitions": {
		"Function1": {
			"type": "object"
		}
	}`

I also tried to set it to `response = classOf[Unit]` with no effect. 

`@ApiOperation(httpMethod = "OPTIONS", response = classOf[String], value = "Some summary")` would fix this but it's not correct. 

Am I doing something wrong or is there a bug in the way this is automatically-derived?

**Comment by pjfanning** [comment]
Ultimately, the swagger docs are generated by swagger-jaxrs library and this is Java based. There is typically a little leakage of some Scala boilerplate stuff like this into the generated swagger json.
I don't think it causes any major side effects.
If it was necessary to fix this, I think we would need to contribute fixes to swagger-jaxrs to allow it to ignore some items or we would need to post-process the swagger-json to exclude the unwanted extras.

**Comment by pjfanning** [comment]
Merged Pull Request
