### ISSUE TITLE
Does SwaggerHttpService really need apiTypes of type scala.reflect.runtime.universe.Type?

### ISSUE THREAD

**Issue by manonthegithub** [swagger-akka-http/swagger-akka-http#46]
As we can see from the code the Type eventually is converted to the Class.
```scala
def getClassForType(t: Type): Class[_] = {
    mirror.runtimeClass(t.typeSymbol.asClass)
  }
```
So why cant we must have apiTypes of type Type instead of Class?
In my case specific case I have class, not Type and have to make redundant and very simple conversions to Type.
The reason for Class is that it is simply available in runtime from object reference, whereas Type is not, which forces you to do unnecessary complicated conversions even though eventually Class is needed.

**Comment by pjfanning** [comment]
https://github.com/pjfanning/swagger-akka-http-sample/blob/master/src/main/scala/com/example/akka/swagger/SwaggerDocService.scala doesn't seem overly complicated to me.

**Comment by manonthegithub** [comment]
As minimun it is redundant  using scala.reflect where it is just not needed, no real difference but redundant conversions inside SwaggerHttpService:
```scala
object SwaggerDocService extends SwaggerHttpService {
  //similar but with classes
  override val apiTypes = Seq(classOf[AddService], classOf[HelloService])
  override val host = "localhost:12345"
  override val info = Info(version = "1.0")
  override val externalDocs = Some(new ExternalDocs("Core Docs", "http://acme.com/docs"))
  override val securitySchemeDefinitions = Map("basicAuth" -> new BasicAuthDefinition())
}
```
Additionally, in my case it doesnt work because I determine concrete type at runtime. I have a bunch of services and just registering them in SwaggerHttpService to be scanned and showed and it is much more convenient to use simple `Class` instead of searching `Type` when I register services at runtime, i.e. I do not know concrete list of services in advance to hardcode them.

**Comment by manonthegithub** [comment]
```scala
def toJavaTypeSet(apiTypes: Seq[Type]): Set[Class[_]] = {
    apiTypes.map(t => getClassForType(t)).toSet
  }

  private lazy val mirror = scala.reflect.runtime.universe.runtimeMirror(getClass.getClassLoader)

  def getClassForType(t: Type): Class[_] = {
    mirror.runtimeClass(t.typeSymbol.asClass)
  }
``` 
Is this really needed in `SwaggerHttpService`  object?

**Comment by pjfanning** [comment]
If you are blocked, could you copy the SwaggerHttpService code into your own code base and modify it for your own usage?
I will look at changing from types to classes but it could take me a while to get back to it.

**Comment by manonthegithub** [comment]
yeah, thanks, I can possibly create PR tomorrow, if you are very busy).

**Comment by pjfanning** [comment]
How about adding a new `val apiClasses: Seq[Class[_]]` and merging the the 2 Seqs? This retains backward compatible support for apiTypes but allows users to use apiClasses instead (or as well).

**Comment by manonthegithub** [comment]
you broke compat since 0.10.0-SNAPSHOT so now master branch is not compatible with previous versions, so I guess it can be now split to two branches, old branch can remain compatible and new one I guess can be refactored with breaking it. What do you think about splitting?

**Comment by pjfanning** [comment]
I like the scala type support and use it in my projects.

**Comment by manonthegithub** [comment]
also made some refactoring)

**Comment by pjfanning** [comment]
Merged Pull Request
