### ISSUE TITLE
OpenAPI 3.0 / Swagger 2.0 support

### ISSUE THREAD

**Issue by pjfanning** [swagger-akka-http/swagger-akka-http#53]
https://www.openapis.org/blog/2017/07/26/the-oai-announces-the-openapi-specification-3-0-0
Swagger 2.0 is still under development. Its annotations are changing quite a lot. When it becomes clearer how to migrate the existing sample to use the 2.0 snapshots, it would be useful to try to get a fork of the sample to output OpenAPI 3.0 docs.

**Comment by pjfanning** [comment]
I have modified my simplest example, a [standalone Java sample](https://github.com/pjfanning/swagger-akka-http-java), to use swagger-2.0.0-rc1.

**Comment by pjfanning** [comment]
I have a scala-based sample at https://github.com/pjfanning/swagger-akka-http-sample/tree/swagger-2.0.0. This uses the swagger 2.0.0 branch of swagger-akk-http. There is still lots of work to reimplement features and get the test coverage rewritten.

**Comment by nmarasoiu** [comment]
Hi, is there currently a way to document OAuth2 secured endpoints and to do implicit flow with SwaggerUI under current integration of Akka-HTTP with Swagger? Or this is dependent upon OpenAPI 3 support? Thank you

**Comment by pjfanning** [comment]
This project is a thin wrapper on the swagger-core jars and the 2.0 release has not been completed yet. I don't use OAuth2 in any projects so have not looked at it.

**Comment by sourcekick** [comment]
> it would be useful to try to get a fork of the sample to output OpenAPI 3.0 docs

We would immediately adopt once this would be available.

**Comment by pjfanning** [comment]
@sourcekick check my 2nd comment above from Sept 9 which has a link

**Comment by GiantToast** [comment]
How close is Swagger 2 / OpenAPI 3 to being included in a official release?

**Comment by pjfanning** [comment]
The Java swagger-api 2.0 libs appear to have just been released. Swagger-akka-http depends on swagger-api swagger-scala-module and this has not been updated to support this yet and last I checked it was a pretty big job to fix it. All in all, I'm not expecting to get around to this in the near term. Hopefully, someone else will look into it.

**Comment by pjfanning** [comment]
I have updated https://github.com/swagger-akka-http/swagger-akka-http/tree/swagger-2.0.0 to use the swagger-core 2.0.0 release. There is still a lot of stuff to fix in the scala modelconverter.
I published a new swagger-akka-http 1.0.0-SNAPSHOT.
https://github.com/pjfanning/swagger-akka-http-sample/tree/swagger-2.0.0 uses this snapshot

**Comment by sourcekick** [comment]
Any updates on this?

**Comment by pjfanning** [comment]
@sourcekick Try the sample - https://github.com/pjfanning/swagger-akka-http-sample/tree/swagger-2.0.0 (note this is a branch)
`"com.github.swagger-akka-http" %% "swagger-akka-http" % "2.0.0-SNAPSHOT"` is available in sonatype snapshots maven repo.

**Comment by pjfanning** [comment]
experimental 2.0.0 release made
