### ISSUE TITLE
HTTP command is not correctly generated when the server is behind a https vip.

### ISSUE THREAD

**Issue by peng-sun** [swagger-akka-http/swagger-akka-http#57]
I am using version 0.11.0.

In my case the server is behind a https vip. The vip redirect a https request to the server's 8080 port. 

My SwaggerDoc class code is simple, like below: 

class SwaggerDoc extends SwaggerHttpService {
  override val apiClasses = Set(
    classOf[service1],
    classOf[service2],
    classOf[service3],
    classOf[service4]
  )
  val contact = new Contact()
  contact.setName("contact1")
  override val info = Info(version = "0.1", title = "Demo", description = "", contact = contact)
}

The problem is if I used the url https://viphost/swagger-ui/index.html?url=/api-docs/swagger.json to visit my swagger UI. The swagger UI can be loaded. But any http request generated from the UI is having the vip hostname with http instead of https. Certainly the result is no response. 

Anything I did wrong or I missed for configure the SwaggerDoc?

**Comment by pjfanning** [comment]
Could you try something like?
`override val schemes = List(Scheme.HTTPS)`

**Comment by peng-sun** [comment]
@pjfanning Thanks for the reply. I followed your recommendation and finally figure it out. 

From my testing result, the best solution is to use following override. 
```override val schemes = List(Scheme.HTTP, Scheme.HTTPS)```

schemes here means allowed schemes. In my testing, it can automatically pick the right protocol (http/https) based on the request url.

I would suggest a change/PR to make the schemes' default value to have both HTTP and HTTPS. Those are common usages, dev and prod environments. With that as default, users do not need to make any override change.
