### ISSUE TITLE
Failing with oracle jdk 9

### ISSUE THREAD

**Issue by vvasuki** [swagger-akka-http/swagger-akka-http#62]
Swagger serving was crashing on my server with the following java version:
```
java -version
java version "9.0.1"
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)
```
The log is here: https://pastebin.com/raw/xDM2w2Gm

The fix was to add a dependency:
`"javax.xml.bind" % "jaxb-api" % "2.3.0",` as indicated by [this thread](https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j).

I guess this should be fixed here or upstream.

**Comment by pjfanning** [comment]
I would suggest this should be fixed in swagger core. The ModelResolver class is part of swagger core.

**Comment by vvasuki** [comment]
Thanks, reported it there. Leaving this open so that you can depend on a release where they've fixed the problem.

**Comment by pjfanning** [comment]
Swagger-Core issue is marked as fixed
