### ISSUE TITLE
Model inheritance/ reusing properties 

### ISSUE THREAD

**Issue by eugenemiretsky** [swagger-akka-http/swagger-akka-http#65]
Usually, a post on a resource doesn't have an id, while a get does. 
For example (Scala code)

    trait UserT(def name: String, def age: Int)
    case class User(name: String, age: Int) extends UserT // Used for Post requests
    case class UserWithid(name: String, age: Int) extends UserT // Used for Post requests

Is it possible to add annotations to the trait, and have the classes reuse it? 
I think the corresponding feature in swagger is: https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/

**Comment by pjfanning** [comment]
This project is just a thin wrapper for swagger-jaxrs. It includes the code that generates the swagger models. I suggest the best course is to use the swagger google group.
