### ISSUE TITLE
Help to generate simple doc for simple annotated class

### ISSUE THREAD

**Issue by copmir** [swagger-akka-http/swagger-akka-http#70]
Hi,

i have created this simple annotated class in scala and used used swagger-akka-http 0.14.0 version

`@Path("/testApiOperation")
@Api(value = "/testApiOperation", description = "Operations about get.")
class Prova {
   @ApiOperation(value = "testiOperation", httpMethod = "GET")
 @ApiResponses(Array(
    new ApiResponse(code = 404, message = "Pong not found"),
    new ApiResponse(code = 200, message = "Pong found"),
    new ApiResponse(code = 400, message = "Invalid Ping supplied")))
def testOperation (@ApiParam(name="page", value="start page") @QueryParam("page") page:String) ={}
}`

when i run the code , and launch  http://localhost:8080/api-docs/swagger.json     i have this error :

java.util.ServiceConfigurationError: io.swagger.converter.ModelConverter: Provider com.github.swagger.akka.SwaggerScalaModelConverter could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
	at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
...........
Caused by: java.lang.VerifyError: Cannot inherit from final class

If i write the procedure testOperation without annotated parameters (@ApiParam) all it's ok:  the documentation is generated.

I have the same problem when try to generate doc for this simply route:
`@ApiOperation(value = "Find a ping", notes = "Returns a pong", httpMethod = "GET", response = classOf[String])
  @ApiResponses(Array(
    new ApiResponse(code = 404, message = "Pong not found"),
    new ApiResponse(code = 200, message = "Pong found"),
    new ApiResponse(code = 400, message = "Invalid Ping supplied")))
  def readRoute = path("ping") {
    complete("pong")
} `

Can you help me please?
Many thanks

**Comment by pjfanning** [comment]
Could you check the swagger and Jackson jar versions you are using?

**Comment by copmir** [comment]
Hi,
my pom.xml has this entries:
```xml
<dependency>
    <groupId>commons-logging</groupId>
    <artifactId>commons-logging</artifactId>
</dependency>
              <dependency>
            <groupId>org.apache.solr</groupId>
            <artifactId>solr-solrj</artifactId>
            <exclusions>
             <exclusion>
            <groupId>*</groupId>
            <artifactId>*</artifactId>
        </exclusion>
        </exclusions>
            </dependency>
        <dependency>
            <groupId>org.apache.solr</groupId>
            <artifactId>solr-core</artifactId>
                 <exclusions>
             <exclusion>
            <groupId>*</groupId>
            <artifactId>*</artifactId>
        </exclusion>
        </exclusions>
        </dependency>

  <dependency>
    <groupId>com.typesafe.akka</groupId>
    <artifactId>akka-http-spray-json_2.12</artifactId>
    <version>10.1.0</version>
</dependency> 
<dependency>
    <groupId>com.github.swagger-akka-http</groupId>
    <artifactId>swagger-akka-http_2.12</artifactId>
    <version>0.14.0</version>
</dependency>
```
The resulting jackson version is 2.9.4, swagger is 1.5.18

**Comment by copmir** [comment]
solved: there is a hidden old version of jackson
