### ISSUE TITLE
recognize Jaxb annotations  

### ISSUE THREAD

**Issue by copmir** [swagger-akka-http/swagger-akka-http#71]
Hi,

i have my model classes annotate with @XmlRootElement, @XmlElement... This classes are annotated as @queryparam in the service class.
It's possible with swagger-akka-http to recognize these jaxb annotations and to visualize the model classes into definitions section of swagger.json? If yes, how?
I have tried, and in the parameters section i find the param with in="query" and type="string" (even if it's a complex object)  but nothing is in definitions section. 

Many thx

**Comment by pjfanning** [comment]
The annotation reading code is in swagger-api project jars. This code base has no such code of its own.
