### ISSUE TITLE
The swagger is generated, but getting error "Multiple body parameters are not allowed." when using the output in https://editor.swagger.io

### ISSUE THREAD

**Issue by avnerbarr** [swagger-akka-http/swagger-akka-http#82]
basically the endpoint is generating the swagger JSON/yaml but when I try to plug it into the editor, I get semantic errors about "Multiple body parameters are not allowed".

Any idea?

**Comment by pjfanning** [comment]
probably same issue as https://github.com/swagger-akka-http/swagger-akka-http/issues/84
