### ISSUE TITLE
basePath removed?

### ISSUE THREAD

**Issue by dalegaspi** [swagger-akka-http/swagger-akka-http#90]
I am using the latest swagger stuff (3.x) and for the `SwaggerDocService` the `basePath` no longer exists (which makes this [portion of the README](https://github.com/swagger-akka-http/swagger-akka-http#swaggerhttpservice) slightly outdated)

is it expected now to explicitly define the base path (like ours always start with `/rest/v1`) in the `@Path` annotations (where applicable)?  it's a slight inconvenience but maybe there is a change the way base path is set and i'm just unaware of it.

thanks!

**Comment by pjfanning** [comment]
The swagger/openapi code changed a lot and it's hard to find docs as to what the transition path is for code that was originally written for swagger 1.5. https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-models/src/main/java/io/swagger/v3/oas/models/OpenAPI.java has a Path/PathItem abstraction and maybe this is what is needed but I'm not sure.

**Comment by pjfanning** [comment]
One way you might be able to get this work is to use the `host` parameter and set it to a value like `hostname:port/base/path` (eg www.acme.com:8080/api/v1).

**Comment by dalegaspi** [comment]
thanks @pjfanning that works and is a good-enough workaround.

**Comment by pjfanning** [comment]
I added back support for basePath in 2.0.2
